# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ticket-swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ticket-swift
    pod 'Alamofire', '~> 4.0'
    pod 'Kingfisher', '~> 5.7.0'

  target 'ticket-swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ticket-swiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
